
export const GET_THEATERMOVIE_REQUEST ="GET_THEATERMOVIE_REQUEST";
export const GET_THEATERMOVIE_SUCCESS ="GET_THEATERMOVIE_SUCCESS";
export const GET_THEATERMOVIE_FAILURE ="GET_THEATERMOVIE_FAILURE";