export const UPDATE_INFO_USER_REQUEST = "UPDATE_INFO_USER_REQUEST";
export const UPDATE_INFO_USER_SUCCESS = "UPDATE_INFO_USER_SUCCESS";
export const UPDATE_INFO_USER_FAILURE = "UPDATE_INFO_USER_FAILURE";
